server:
  port: 9999
#spring:
#  data:
#    elasticsearch:
#      client:
#        reactive:
#          endpoints:

spring:
  elasticsearch:
    rest:
      uris:
            - 192.168.147.131:9200
      username: elastic
      password: 123456
